apiVersion: apps/v1
kind: Deployment
metadata:
  name: splitdim
  labels:
    app: splitdim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: splitdim
  template:
    metadata:
      labels:
        app: splitdim
    spec:
      terminationGracePeriodSeconds: 600
      containers:
      - name: splitdim
        image: localhost/splitdim
        ports:
        - containerPort: 8080
        env:
        - name: KVSTORE_MODE
          valueFrom:
            configMapKeyRef:
              name: splitdim-config
              key: kvstoreMode
              optional: false
        - name: KVSTORE_ADDR
          valueFrom:
            configMapKeyRef:
              name: splitdim-config
              key: kvstoreAddr
              optional: true
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: splitdim
spec:
  selector:
    app: splitdim
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: splitdim-config
data:
  kvstoreMode: "kvstore"
  kvstoreAddr: "kvstore.default:8081"
