apiVersion: apps/v1
kind: Deployment
metadata:
  name: splitdim
  labels:
    app: splitdim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: splitdim
  template:
    metadata:
      labels:
        app: splitdim
    spec:
      containers:
      - name: splitdim
        # Itt hagytam a te image nevedet, de ne felejtsd el frissíteni (push)!
        image: szabodora237/splitdim:latest 
        imagePullPolicy: Never  # Ez segít, hogy biztosan az új verziót töltse le
        ports:
        - containerPort: 8080
        env:
        - name: KVSTORE_MODE
          value: "resilientkvstore"  # <--- ÁTÍRVA: "local" helyett "resilientkvstore"
        - name: KVSTORE_ADDR
          value: "kvstore:8081"        # <--- HOZZÁADVA: Meg kell mondani, hol a db
        resources:                   # <--- HOZZÁADVA: Biztonsági limit a retry teszthez
          requests:
            cpu: "100m"
          limits:
            cpu: "100m"
