apiVersion: apps/v1
kind: Deployment
metadata:
  name: splitdim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: splitdim
  template:
    metadata:
      labels:
        app: splitdim
    spec:
      containers:
        - name: splitdim
          image: splitdim:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: splitdim
spec:
  type: LoadBalancer
  selector:
    app: splitdim
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
